# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wheather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireObjectMapper', '~> 5.2'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
    pod 'FirebaseFirestore'
    pod 'Sync', '~> 5'
    pod 'Toast-Swift', '~> 5.0.0'
  # Pods for Wheather

  target 'WheatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WheatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
